export const employees = [
  {
    id: 1,
    name: "Amit Sharma",
    position: "Software Engineer",
    department: "Engineering",
    email: "amit.sharma@example.com",
    phone: "+91-9876543210",
    location: "Delhi",
    status: "Active",
    joiningDate: "2022-05-10",
  },
  {
    id: 2,
    name: "Priya Mehta",
    position: "HR Manager",
    department: "Human Resources",
    email: "priya.mehta@example.com",
    phone: "+91-9988776655",
    location: "Mumbai",
    status: "Active",
    joiningDate: "2020-03-15",
  },
  {
    id: 3,
    name: "Rajiv Kapoor",
    position: "Product Manager",
    department: "Product",
    email: "rajiv.kapoor@example.com",
    phone: "+91-9123456789",
    location: "Bangalore",
    status: "On Leave",
    joiningDate: "2019-11-01",
  },
  {
    id: 4,
    name: "Sneha Rathi",
    position: "UI/UX Designer",
    department: "Design",
    email: "sneha.rathi@example.com",
    phone: "+91-9012345678",
    location: "Hyderabad",
    status: "Active",
    joiningDate: "2021-07-22",
  },
  {
    id: 5,
    name: "Karan Verma",
    position: "DevOps Engineer",
    department: "Infrastructure",
    email: "karan.verma@example.com",
    phone: "+91-9090909090",
    location: "Pune",
    status: "Inactive",
    joiningDate: "2018-01-12",
  }
];
